In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Pandas works only on series or dataframes
#s=pd.Series([1,2,3,4])
s=pd.Series([1,2,3,4], index=['a','b','c','d'])
print(s)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
data={'name':['ansh','Deepak','Kirti'],'age':[17,18,17],'marks':[95,96,94]}
df=pd.DataFrame(data)

In [ ]:
df

     name  age  marks
0    ansh   17     95
1  Deepak   18     96
2   Kirti   17     94

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'students-performance-in-exams' dataset.
Path to dataset files: /kaggle/input/students-performance-in-exams

In [ ]:
#df1=pd.read_excel("/content/sales.excel")
df=pd.read_csv("/kaggle/input/students-performance-in-exams/StudentsPerformance.csv") # use forward slashes in path of file.
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.head()

   Sale_ID        Date  Store_ID  Product_ID  Units
0        1  2022-01-01        24           4      1
1        2  2022-01-01        28           1      1
2        3  2022-01-01         6           8      1
3        4  2022-01-01        48           7      1
4        5  2022-01-01        44          18      1

In [ ]:
df.head(8)

   Sale_ID        Date  Store_ID  Product_ID  Units
0        1  2022-01-01        24           4      1
1        2  2022-01-01        28           1      1
2        3  2022-01-01         6           8      1
3        4  2022-01-01        48           7      1
4        5  2022-01-01        44          18      1
5        6  2022-01-01         1          31      1
6        7  2022-01-01        40           7      1
7        8  2022-01-01        19           2      1

In [ ]:
df.tail()

        Sale_ID        Date  Store_ID  Product_ID  Units
829257   829258  2023-09-30        24          19      1
829258   829259  2023-09-30        16          35      1
829259   829260  2023-09-30        22          19      1
829260   829261  2023-09-30        13           2      2
829261   829262  2023-09-30        32           6      1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 829262 entries, 0 to 829261
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Sale_ID     829262 non-null  int64
 1   Date        829262 non-null  object
 2   Store_ID    829262 non-null  int64
 3   Product_ID  829262 non-null  int64
 4   Units       829262 non-null  int64
dtypes: int64(4), object(1)
memory usage: 31.6+ MB

In [ ]:
df.describe()

             Sale_ID       Store_ID     Product_ID          Units
count  829262.000000  829262.000000  829262.000000  829262.000000
mean   414631.500000      25.277034      15.014149       1.315103
std    239387.463803      14.352573       9.869417       0.830701
min         1.000000       1.000000       1.000000       1.000000
25%    207316.250000      13.000000       6.000000       1.000000
50%    414631.500000      26.000000      14.000000       1.000000
75%    621946.750000      38.000000      24.000000       1.000000
max    829262.000000      50.000000      35.000000      30.000000

In [ ]:
df.shape

(829262, 5)

In [ ]:
df.columns

Index(['Sale_ID', 'Date', 'Store_ID', 'Product_ID', 'Units'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=829262, step=1)

In [ ]:
df["Sale_ID"]

0              1
1              2
2              3
3              4
4              5
           ...
829257    829258
829258    829259
829259    829260
829260    829261
829261    829262
Name: Sale_ID, Length: 829262, dtype: int64

In [ ]:
df.iloc[50]

Sale_ID               51
Date          2022-01-01
Store_ID              21
Product_ID             8
Units                  1
Name: 50, dtype: object

In [ ]:
df.index[50]

50

In [ ]:
dict1={"Names":["ayush", "Sukirti","Amit","Diksha"],"Gender":["Male","Female","Male","Female"],"Department":["IT","Management","HR","IT"],'Age':[21,20,20,21]}
df1=pd.DataFrame(dict1)
df1

     Names  Gender  Department  Age
0    ayush    Male          IT   21
1  Sukirti  Female  Management   20
2     Amit    Male          HR   20
3   Diksha  Female          IT   21

In [ ]:
#value counts
df1["Gender"].value_counts()

Gender
Male      2
Female    2
Name: count, dtype: int64

In [ ]:
df1["Department"].unique()

array(['IT', 'Management', 'HR'], dtype=object)

In [ ]:
df.isnull().sum()

Sale_ID       0
Date          0
Store_ID      0
Product_ID    0
Units         0
dtype: int64

In [ ]:
df1.isnull().sum()

Names         0
Gender        0
Department    0
Age           0
dtype: int64

In [ ]:
df.shape

(829262, 5)

In [ ]:
#Drop column
df1.drop("Age",axis=1)

     Names  Gender  Department
0    ayush    Male          IT
1  Sukirti  Female  Management
2     Amit    Male          HR
3   Diksha  Female          IT

In [ ]:
df1.drop(1)

    Names  Gender Department  Age
0   ayush    Male         IT   21
2    Amit    Male         HR   20
3  Diksha  Female         IT   21

In [ ]:
# drop null values
df1.dropna()

     Names  Gender  Department  Age
0    ayush    Male          IT   21
1  Sukirti  Female  Management   20
2     Amit    Male          HR   20
3   Diksha  Female          IT   21

In [ ]:























#replacing null values
df1.fillna(0)
df["Age"].fillna(df["Age"].mean())
df["Department"].fillna(df["Department"].mode())

#joins
#merge, concat

KeyError: 'Age'